import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";

/** Internal quality/safety reports. Deliberately separate from incident_reports,
 * which stores incoming accident and injury cases. */
export const ovrReportsTable = sqliteTable("ovr_reports", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  reportNumber: text("report_number").notNull().unique(),
  eventDate: integer("event_date", { mode: "timestamp_ms" }).notNull(),
  eventTime: text("event_time"),
  department: text("department").notNull(),
  location: text("location").notNull(),
  eventType: text("event_type").notNull(),
  patientName: text("patient_name"),
  fileNumber: text("file_number"),
  hospitalSupervision: text("hospital_supervision"),
  administrativeManager: text("administrative_manager"),
  severity: text("severity").notNull().default("no_harm"),
  description: text("description").notNull(),
  immediateAction: text("immediate_action"),
  reporterName: text("reporter_name").notNull(),
  reporterRole: text("reporter_role"),
  investigatorName: text("investigator_name"),
  investigationDate: integer("investigation_date", { mode: "timestamp_ms" }),
  status: text("status").notNull().default("new"),
  investigationSummary: text("investigation_summary"),
  rootCause: text("root_cause"),
  correctiveAction: text("corrective_action"),
  preventiveAction: text("preventive_action"),
  actionOwner: text("action_owner"),
  dueDate: integer("due_date", { mode: "timestamp_ms" }),
  verificationNotes: text("verification_notes"),
  reviewedBy: text("reviewed_by"),
  reviewedAt: integer("reviewed_at", { mode: "timestamp_ms" }),
  closedBy: text("closed_by"),
  closedAt: integer("closed_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).$defaultFn(() => new Date()).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).$defaultFn(() => new Date()).notNull(),
});

export type OvrReport = typeof ovrReportsTable.$inferSelect;
